CREATE TABLE IF NOT EXISTS films (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  release_date timestamp NOT NULL,
  duration integer,
  rating_id integer REFERENCES rating(id)
);

CREATE TABLE IF NOT EXISTS rating (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id LONG AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(200),
  login VARCHAR(255),
  name VARCHAR(255),
  birthday timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users(id),
	film_id BIGINT NOT NULL REFERENCES films(id)
);

CREATE TABLE IF NOT EXISTS FRIENDSHIPS (
	USER_ID LONG NOT NULL REFERENCES users(id),
	FRIEND_ID LONG NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS film_genres (
	FILM_ID LONG NOT NULL REFERENCES films(id),
	GENRE_ID INTEGER NOT NULL REFERENCES genre(id)
);